# -*- coding: utf-8 -*-
"""PyMySQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rO5TBOKfp3oVLmjtbk-Apkvd9xsPPiR
"""

import pymysql
db = pymysql.connect("imc.kean.edu","panjin","1025761","CPS3740" )
cursor = db.cursor()
sql = "SELECT * FROM Booking"

try:
   cursor.execute(sql)
   results = cursor.fetchall()
   for row in results:
      hotelno = row[0]
      guestno = row[1]
      datefrom = row[2]
      dateto = row[3]
      roomno = row[4]

      print ("hotelno=%s,guestno=%s,datefrom=%s,dateto=%s,roomno=%s" % \
             (hotelno, guestno, datefrom, dateto, roomno ))
except:
   print ("Error: unable to fetch data")
 
db.close()